### ISSUE TITLE
[Bug] Config is dumped with recursive references

### ISSUE THREAD

**Issue by lauriebax** [open-mmlab/mmengine#1234]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmengine/issues) and [Discussions](https://github.com/open-mmlab/mmengine/discussions) but cannot get the expected help.
- [ ] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmengine).

### Environment

```
OrderedDict([('sys.platform', 'linux'),
             ('Python',
              '3.8.13 | packaged by conda-forge | (default, Mar 25 2022, '
              '06:04:10) [GCC 10.3.0]'),
             ('CUDA available', True),
             ('numpy_random_seed', 2147483648),
             ('GPU 0', 'NVIDIA GeForce RTX 3060 Laptop GPU'),
             ('CUDA_HOME', '/usr/local/cuda'),
             ('NVCC', 'Cuda compilation tools, release 11.6, V11.6.124'),
             ('GCC', 'gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0'),
             ('PyTorch', '1.12.0a0+bd13bc6'),
             ('PyTorch compiling details',
              'PyTorch built with:\n'
              '  - GCC 9.4\n'
              '  - C++ Version: 201402\n'
              '  - Intel(R) Math Kernel Library Version 2019.0.5 Product Build '
              '20190808 for Intel(R) 64 architecture applications\n'
              '  - Intel(R) MKL-DNN v2.5.2 (Git Hash N/A)\n'
              '  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n'
              '  - LAPACK is enabled (usually provided by MKL)\n'
              '  - NNPACK is enabled\n'
              '  - CPU capability usage: AVX2\n'
              '  - CUDA Runtime 11.6\n'
              '  - NVCC architecture flags: '
              '-gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_86,code=compute_86\n'
              '  - CuDNN 8.4\n'
              '  - Magma 2.5.2\n'
              '  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, '
              'CUDA_VERSION=11.6, CUDNN_VERSION=8.4.0, '
              'CXX_COMPILER=/usr/bin/c++, CXX_FLAGS=-fno-gnu-unique '
              '-fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG '
              '-DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK '
              '-DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE '
              '-DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall '
              '-Wextra -Werror=return-type -Wno-missing-field-initializers '
              '-Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas '
              '-Wno-sign-compare -Wno-unused-parameter -Wno-unused-function '
              '-Wno-unused-result -Wno-unused-local-typedefs '
              '-Wno-strict-overflow -Wno-strict-aliasing '
              '-Wno-error=deprecated-declarations -Wno-stringop-overflow '
              '-Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls '
              '-Wno-error=old-style-cast -fdiagnostics-color=always '
              '-faligned-new -Wno-unused-but-set-variable '
              '-Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math '
              '-Werror=format -Werror=cast-function-type '
              '-Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, '
              'PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.0, '
              'USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, '
              'USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=ON, '
              'USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, \n'),
             ('TorchVision', '0.13.0a0'),
             ('OpenCV', '4.8.0'),
             ('MMEngine', '0.7.4')])
```

### Reproduces the problem - code sample

When using a YAML file to load e.g. upernet_tiny the yaml is resolved to have cyclic dependencies. E.g. when using 
lists inside a tta_pipeline when loading from python file

Input, e.g. tta.py:
```python
tta_pipeline = [
    dict(type='LoadImageFromFile', backend_args=None),
    dict(
        type='TestTimeAug',
        transforms=[
            [
                dict(type='Resize', scale_factor=r, keep_ratio=True)
                for r in img_ratios
            ],
            [
                dict(type='RandomFlip', prob=0., direction='horizontal'),
                dict(type='RandomFlip', prob=1., direction='horizontal')
            ], [dict(type='LoadAnnotations')], [dict(type='PackSegInputs')]
        ])
]
```
Which is use in e.g. a yaml
```yaml
_base_: tta.py
```

Output:
```
...
tta_model:
  type: SegTTAModel
tta_pipeline:
- backend_args: null
  type: LoadImageFromFile
- transforms:
  - - &id001 !!python/object/new:mmengine.config.config.ConfigDict
      args:
      - !!python/tuple
        - type
        - Resize
      - !!python/tuple
        - scale_factor
        - 0.5
      - !!python/tuple
        - keep_ratio
        - true
      dictitems:
        keep_ratio: true
        scale_factor: 0.5
        type: Resize
      state: *id001
    - &id002 !!python/object/new:mmengine.config.config.ConfigDict
      args:
      - !!python/tuple
        - type
        - Resize
      - !!python/tuple
        - scale_factor
        - 0.75
      - !!python/tuple
        - keep_ratio
        - true
      dictitems:
        keep_ratio: true
        scale_factor: 0.75
        type: Resize
      state: *id002
    - &id003 !!python/object/new:mmengine.config.config.ConfigDict
      args:
      - !!python/tuple
        - type
        - Resize
      - !!python/tuple
        - scale_factor
        - 1.0
      - !!python/tuple
        - keep_ratio
        - true
      dictitems:
        keep_ratio: true
        scale_factor: 1.0
        type: Resize
      state: *id003
    - &id004 !!python/object/new:mmengine.config.config.ConfigDict
      args:
      - !!python/tuple
        - type
        - Resize
      - !!python/tuple
        - scale_factor
        - 1.25
      - !!python/tuple
        - keep_ratio
        - true
      dictitems:
        keep_ratio: true
        scale_factor: 1.25
        type: Resize
      state: *id004
    - &id005 !!python/object/new:mmengine.config.config.ConfigDict
      args:
      - !!python/tuple
        - type
        - Resize
      - !!python/tuple
        - scale_factor
        - 1.5
      - !!python/tuple
        - keep_ratio
        - true
      dictitems:
        keep_ratio: true
        scale_factor: 1.5
        type: Resize
      state: *id005
    - &id006 !!python/object/new:mmengine.config.config.ConfigDict
      args:
      - !!python/tuple
        - type
        - Resize
      - !!python/tuple
        - scale_factor
        - 1.75
      - !!python/tuple
        - keep_ratio
        - true
      dictitems:
        keep_ratio: true
        scale_factor: 1.75
        type: Resize
      state: *id006
  - - &id007 !!python/object/new:mmengine.config.config.ConfigDict
      args:
      - !!python/tuple
        - type
        - RandomFlip
      - !!python/tuple
        - prob
        - 0.0
      - !!python/tuple
        - direction
        - horizontal
      dictitems:
        direction: horizontal
        prob: 0.0
        type: RandomFlip
      state: *id007
    - &id008 !!python/object/new:mmengine.config.config.ConfigDict
      args:
      - !!python/tuple
        - type
        - RandomFlip
      - !!python/tuple
        - prob
        - 1.0
      - !!python/tuple
        - direction
        - horizontal
      dictitems:
        direction: horizontal
        prob: 1.0
        type: RandomFlip
      state: *id008
  - - &id009 !!python/object/new:mmengine.config.config.ConfigDict
      args:
      - !!python/tuple
        - type
        - LoadAnnotations
      dictitems:
        type: LoadAnnotations
      state: *id009
  - - &id010 !!python/object/new:mmengine.config.config.ConfigDict
      args:
      - !!python/tuple
        - type
        - PackSegInputs
      dictitems:
        type: PackSegInputs
      state: *id010
  type: TestTimeAug
...
```

### Reproduces the problem - command or script

```python

cfg = Config.fromfile(config_path)
runner = Runner.from_cfg(cfg)

```

### Reproduces the problem - error message

```
/opt/conda/lib/python3.8/site-packages/mmengine/fileio/handlers/base.py:26: in load_from_path
    return self.load_from_fileobj(f, **kwargs)
/opt/conda/lib/python3.8/site-packages/mmengine/fileio/handlers/yaml_handler.py:17: in load_from_fileobj
    return yaml.load(file, **kwargs)
/opt/conda/lib/python3.8/site-packages/yaml/__init__.py:81: in load
    return loader.get_single_data()
/opt/conda/lib/python3.8/site-packages/yaml/constructor.py:51: in get_single_data
    return self.construct_document(node)
/opt/conda/lib/python3.8/site-packages/yaml/constructor.py:60: in construct_document
    for dummy in generator:
/opt/conda/lib/python3.8/site-packages/yaml/constructor.py:408: in construct_yaml_seq
    data.extend(self.construct_sequence(node))
/opt/conda/lib/python3.8/site-packages/yaml/constructor.py:129: in construct_sequence
    return [self.construct_object(child, deep=deep)
/opt/conda/lib/python3.8/site-packages/yaml/constructor.py:129: in <listcomp>
    return [self.construct_object(child, deep=deep)
/opt/conda/lib/python3.8/site-packages/yaml/constructor.py:102: in construct_object
    data = constructor(self, tag_suffix, node)
/opt/conda/lib/python3.8/site-packages/yaml/constructor.py:659: in construct_python_object_new
    return self.construct_python_object_apply(suffix, node, newobj=True)
/opt/conda/lib/python3.8/site-packages/yaml/constructor.py:642: in construct_python_object_apply
    value = self.construct_mapping(node, deep=True)
/opt/conda/lib/python3.8/site-packages/yaml/constructor.py:218: in construct_mapping
    return super().construct_mapping(node, deep=deep)
/opt/conda/lib/python3.8/site-packages/yaml/constructor.py:143: in construct_mapping
    value = self.construct_object(value_node, deep=deep)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <yaml.cyaml.CLoader object at 0x55de8ac6af20>
node = MappingNode(tag='tag:yaml.org,2002:python/object/new:mmengine.config.config.ConfigDict', value=[(ScalarNode(tag='tag:y...alue='state'), MappingNode(tag='tag:yaml.org,2002:python/object/new:mmengine.config.config.ConfigDict', value=[...]))])
deep = True

    def construct_object(self, node, deep=False):
        if node in self.constructed_objects:
            return self.constructed_objects[node]
        if deep:
            old_deep = self.deep_construct
            self.deep_construct = True
        if node in self.recursive_objects:
>           raise ConstructorError(None, None,
                    "found unconstructable recursive node", node.start_mark)
E           yaml.constructor.ConstructorError: found unconstructable recursive node
E             in "/tmp/pytest-of-root/pytest-28/test_train_semantic_unet_upern0/experiments/semantic-segmentation/20230704-095343__upernet_convnext_tiny/framework_config.yaml", line 327, column 7

/opt/conda/lib/python3.8/site-packages/yaml/constructor.py:74: ConstructorError
```

### Additional information

1.Expections: I can load the yaml file which is dumped by mmengine runner.
